/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AcsadminRouteImport } from './routes/acsadmin'
import { Route as AcessRouteImport } from './routes/acess'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWebhookCaktoRouteImport } from './routes/api/public/webhook/cakto'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AcsadminRoute = AcsadminRouteImport.update({
  id: '/acsadmin',
  path: '/acsadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessRoute = AcessRouteImport.update({
  id: '/acess',
  path: '/acess',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookCaktoRoute = ApiPublicWebhookCaktoRouteImport.update({
  id: '/api/public/webhook/cakto',
  path: '/api/public/webhook/cakto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acess': typeof AcessRoute
  '/acsadmin': typeof AcsadminRoute
  '/agenda': typeof AgendaRoute
  '/dashboard': typeof DashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/webhook/cakto': typeof ApiPublicWebhookCaktoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acess': typeof AcessRoute
  '/acsadmin': typeof AcsadminRoute
  '/agenda': typeof AgendaRoute
  '/dashboard': typeof DashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/webhook/cakto': typeof ApiPublicWebhookCaktoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acess': typeof AcessRoute
  '/acsadmin': typeof AcsadminRoute
  '/agenda': typeof AgendaRoute
  '/dashboard': typeof DashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/webhook/cakto': typeof ApiPublicWebhookCaktoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acess'
    | '/acsadmin'
    | '/agenda'
    | '/dashboard'
    | '/reset-password'
    | '/api/public/webhook/cakto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acess'
    | '/acsadmin'
    | '/agenda'
    | '/dashboard'
    | '/reset-password'
    | '/api/public/webhook/cakto'
  id:
    | '__root__'
    | '/'
    | '/acess'
    | '/acsadmin'
    | '/agenda'
    | '/dashboard'
    | '/reset-password'
    | '/api/public/webhook/cakto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessRoute: typeof AcessRoute
  AcsadminRoute: typeof AcsadminRoute
  AgendaRoute: typeof AgendaRoute
  DashboardRoute: typeof DashboardRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicWebhookCaktoRoute: typeof ApiPublicWebhookCaktoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acsadmin': {
      id: '/acsadmin'
      path: '/acsadmin'
      fullPath: '/acsadmin'
      preLoaderRoute: typeof AcsadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acess': {
      id: '/acess'
      path: '/acess'
      fullPath: '/acess'
      preLoaderRoute: typeof AcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/cakto': {
      id: '/api/public/webhook/cakto'
      path: '/api/public/webhook/cakto'
      fullPath: '/api/public/webhook/cakto'
      preLoaderRoute: typeof ApiPublicWebhookCaktoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessRoute: AcessRoute,
  AcsadminRoute: AcsadminRoute,
  AgendaRoute: AgendaRoute,
  DashboardRoute: DashboardRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicWebhookCaktoRoute: ApiPublicWebhookCaktoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
